### ISSUE TITLE
ld-toggle component needs some fine tuning

### ISSUE THREAD

**Issue by borisdiakur** [emdgroup-liquid/liquid#11]
`aria-disabled`: works, but some documentation would be cool , similar to https://emdgroup-liquid.github.io/liquid/components/ld-input/#disabled

`mode="large"` should be `size="lg"`, so that we stay consistent with other components (see https://emdgroup-liquid.github.io/liquid/components/ld-button/#size for example)

There is a difference at [https://emdgroup-liquid.github.io/liquid/components/ld-toggle/#with-label](https://emdgroup-liquid.github.io/liquid/components/ld-toggle/#with-label) between the Web Component example and the CSS Component example. Please remove the `required` attribute on the CSS component, so that both examples show the same result.

**Comment by renet** [comment]
`aria-disabled` is already documented: https://emdgroup-liquid.github.io/liquid/components/ld-toggle/#disabled
