### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by borisdiakur** [emdgroup-liquid/liquid#139]
<img width="761" alt="Screenshot 2021-11-22 at 13 49 34" src="https://user-images.githubusercontent.com/527049/142864675-8cc20b4a-27a1-4d88-a513-8fc3c6eb1df1.png">

See https://www.figma.com/file/JcDMeUwec9e185HfBgT9XE/Liquid-Oxygen?node-id=1084%3A6895

Depends on #132

**Comment by borisdiakur** [comment]
This repository is using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for features. This means:
- Feature requests are closed issues with `feature` label and `needed: votes` label.
- Bugs are open issues tagged with the bug label.

Upvote the description (top comment) of this issue with 👍 if you want it to be prioritized higher.

**Comment by zemirco** [comment]
Very nice! I cannot wait to use that in production 🎉 👏
