### ISSUE TITLE
React Bindings: Property 'xy' does not exist on type [...] (TypeScript)

### ISSUE THREAD

**Issue by renet** [emdgroup-liquid/liquid#156]
**Bug description**

When using React Bindings, as soon as I want to add a prop that is not explicitly defined in the component class, a TS error is raised stating, for example:

```
TypeScript error in /dev/project/src/components/Component/Component.tsx(335,61):
Type '{ children: string; onClick: MouseEventHandler<HTMLLdButtonElement>; mode: "secondary"; type: string; }' is not assignable to type 'IntrinsicAttributes & Pick<LdButton & Omit<HTMLAttributes<HTMLLdButtonElement>, "style"> & StyleReactProps, "title" | ... 260 more ... | "justifyContent"> & RefAttributes<...>'.
  Property 'type' does not exist on type 'IntrinsicAttributes & Pick<LdButton & Omit<HTMLAttributes<HTMLLdButtonElement>, "style"> & StyleReactProps, "title" | ... 260 more ... | "justifyContent"> & RefAttributes<...>'.  TS2322
```

This happens, even though we allow for unknown properties and forward them to the inner element in many cases.

**Expected behavior**

A TypeScript definition is used that allows all known props of the element that the props are forwarded to. So for example, if props are forwarded to a `button` element used inside the `ld-button` component, I want to be able to pass all browser-supported props of a `button` element to the `ld-button`. This works for web components as well as for React components.

**Actual behavior**

Props need to be explicitly defined via the `Prop()` decorator in a component in order to pass them to a React component.

**Additional context**

Using

- react@17.0.2
- typescript@4.1.2

with TS strict mode, in an app developed using create-react-app and craco.

**Comment by borisdiakur** [comment]
This will be fixed as soon as we have added explicit prop definitions to all relevant components.

Closing in favour of #157
