### ISSUE TITLE
Ghost Button on Brand Color

### ISSUE THREAD

**Issue by toastedtoast** [emdgroup-liquid/liquid#175]
**Is your feature request related to a problem? Please describe.**
In some cases I need a Button on Brand color which does not show a white border as the Secondary on Brand Button mode.

**Describe the solution you'd like**
Add a new button mode for `ghost-on-brand-color` which does not show a border.

**Comment by borisdiakur** [comment]
Note: This repo is using [Lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736), meaning that closed issues with `feature` and `needed: votes` label end up in our [feature backlog](https://github.com/emdgroup-liquid/liquid/issues?q=sort%3Areactions-%2B1-desc+label%3Afeature+label%3A"needed%3A+votes") and can be voten on with a 👍 emoji reaction.

**Comment by renet** [comment]
I'd suggest dividing the `on-brand-color`-part from the `mode` prop, so that one can freely combine `mode="secondary"` and `mode="ghost"` with a separate `on-brand-color` prop, like so:

```js
<ld-button mode="ghost" on-brand-color>Click me</ld-button>
```

Modes "highlight" and "danger" may simply ignore the `on-brand-color` prop.

**Comment by borisdiakur** [comment]
@NicolasBlock91 👋

**Comment by renet** [comment]
This feature request also relates to #135, as the Header requires the "ghost on brand color" state for icons. I'll start working on a PR for this now.
