### ISSUE TITLE
Input component not triggering onChange.

### ISSUE THREAD

**Issue by m-suyash-kale** [emdgroup-liquid/liquid#182]
**Bug description**
While using React Input component, the onChange method is not triggered.

**Steps to reproduce the behavior**
Use a React Input component & pass a function to the onChange property. Change the value of the Input component.

**Expected behavior**
onChange function should be triggered.

**Actual behavior**
onChange function is not triggered.

**Additional context**
https://codesandbox.io/s/liquid-oxygen-input-0ikq1

**Comment by borisdiakur** [comment]
Thanks @m-suyash-kale 
Workaround until we fix this: Use `onInput` instead.

**Comment by m-suyash-kale** [comment]
@borisdiakur: Thanks for your response, the workaround works perfectly!

**Comment by renet** [comment]
This may also relate to #153

**Comment by borisdiakur** [comment]
This will be fixed with https://github.com/emdgroup-liquid/liquid/pull/188 in the upcoming release.
See https://github.com/emdgroup-liquid/liquid/pull/188#discussion_r779386207 for details.
