### ISSUE TITLE
Web components: `<ld-button>`, `<ld-checkbox> ` and `<ld-input>` not working since `v1.0.0-rc.10`.

### ISSUE THREAD

**Issue by EdisonArango** [emdgroup-liquid/liquid#190]
**Bug description**

Web components like `<ld-button>`, `<ld-checkbox> ` and `<ld-input>` not working since `v1.0.0-rc.10`.

**Steps to reproduce the behavior**

1. Create a file named `app.ts` with the following content
```ts
import { defineCustomElements } from '@emdgroup-liquid/liquid'

defineCustomElements()
```
2. Install [esbuild](https://esbuild.github.io/)
3. Generate the bundle: `npx esbuild app.ts --bundle --outfile=app.js`
4. Open an HTML that loads app.js and contains the web components.

**Expected behavior**

The web components should work.

**Actual behavior**

They are not even rendered, this error appears in the console when using `v1.0.0-rc.10`:

```
DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
```

And this one when using `v1.0.0-rc.20`:

```
DOMException: Failed to execute 'setAttribute' on 'Element': '-e-l-e-m-e-n-t_-n-o-d-e' is not a valid attribute name.
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9254495/145661832-7d14dbe3-d560-49fb-b761-5566011f7d0a.png)

**Details about device, OS, browser (including versions)**

- Device: Macbook Pro M1 2020
- OS: macOS Big Sur v11.6
- Browser: Chrome v96

**Additional context**

All components work when using `v1.0.0-rc.9`, but I only manage to make `<ld-select>` work in the newer versions.

**Comment by borisdiakur** [comment]
Thank you @EdisonArango ! I can reproduce this when using esbuild and with Vite as well.

@renet `ld-loading` is also still working. It must be related to our [`cloneAttributes`](https://github.com/emdgroup-liquid/liquid/blob/d468293ba259ae0ae1dd9357dc1cb119705126af/src/liquid/utils/cloneAttributes.ts#L1) utility function 😣

**Comment by borisdiakur** [comment]
The solution shipped with rc.21 is a quick-fix. We are still working on a better solution which makes sure that you can change props on the host element directly in a way that they are reflected as props on the element that needs to have these props applied within the shadow dom.

What we currently have:

```js
document.querySelector('ld-button').value = 'yolo'
console.log(document.querySelector('ld-button').shadowRoot.querySelector('button').value) // -> ''
```

What we want:

```js
document.querySelector('ld-button').value = 'yolo'
console.log(document.querySelector('ld-button').shadowRoot.querySelector('button').value) // -> 'yolo'
```

**Comment by borisdiakur** [comment]
Closing. Will deal with what I mentioned in my comment above in a separate issue.

**Comment by EdisonArango** [comment]
I confirm it's now working on v1.0.0, thank you!
