### ISSUE TITLE
setAssetPath missing

### ISSUE THREAD

**Issue by m-suyash-kale** [emdgroup-liquid/liquid#213]
**Bug description**
"setAssetPath" is missing in @emdgroup-liquid/liquid@1.0.0-rc.23

**Steps to reproduce the behavior**
`npm i @emdgroup-liquid/liquid;`
`import { setAssetPath } from "@emdgroup-liquid/liquid";`

**Expected behavior**
`setAssetPath` should be a function.

**Actual behavior**
`setAssetPath` is undefined.

**Additional context**
https://codesandbox.io/s/recursing-ully-ceihb?file=/src/App.tsx:61-116

**Comment by borisdiakur** [comment]
Thanks for this @m-suyash-kale 🙏

Please try the following: `import { setAssetPath } from '@emdgroup-liquid/liquid/dist/components'`

We will update the docs in the meantime.

Reason for the regression is that we have removed custom-elements-bundle from liquid as it has been deprecated recently. See https://stenciljs.com/docs/custom-elements-bundle. And then we forgot to update this part of the docs. 😣

**Comment by m-suyash-kale** [comment]
Thanks, @borisdiakur for your quick help. :)
