### ISSUE TITLE
Liquid Oxygen - Input disabled

### ISSUE THREAD

**Issue by m-suyash-kale** [emdgroup-liquid/liquid#214]
**Bug description**
The background of the disabled input should be grey.

**Steps to reproduce the behavior**
Add disabled property to a `LdInput` component.

**Expected behavior**
The background of the input should be grey.

**Actual behavior**
The background of the input is white.

**Additional context**
https://emdgroup-liquid.github.io/liquid/components/ld-input/#disabled
https://codesandbox.io/s/liquid-oxygen-input-disabled-96bkj?file=/src/App.tsx:233-240

**Comment by borisdiakur** [comment]
@NicolasBlock91 Can you have a look at this please ☝️
