### ISSUE TITLE
Add "Remove" icon with minus 

### ISSUE THREAD

**Issue by juliuskittler** [emdgroup-liquid/liquid#215]
**Is your feature request related to a problem? Please describe.**

Under Icons>Modifiers, there is an "Add" icon with a "+" (plus). However, there is nothing like a "Remove" icon with a "-" (minus). It would be great if such an icon could be added to complement the "Add" icon.

**Comment by borisdiakur** [comment]
Thanks you @juliuskittler 🙏 This issue is now managed on our [feature backlog](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+label%3Afeature+-label%3Adone+).

**Comment by borisdiakur** [comment]
@NicolasBlock91 ☝️

**Comment by NicolasBlock91** [comment]
@juliuskittler 
https://www.figma.com/file/8GYcAOePm8Tt9qqJ7Gnv99/Liquid-Oxygen-(Share)?node-id=311%3A21997
Added, please check. 🙂

**Comment by juliuskittler** [comment]
@NicolasBlock91 the icons look good to me!
