### ISSUE TITLE
Button is always disabled

### ISSUE THREAD

**Issue by ElectricCookie** [emdgroup-liquid/liquid#229]
**Bug description**

When passing the disabled prop to the LdButton component (in React) it is always disabled even when passing disabled={false}

**Steps to reproduce the behavior**

```tsx
 <LdButton disabled={false}>
Test
</LdButton>
```

**Expected behavior**

Disabled false should mean enabled

**Actual behavior**

Button is disabled

**Screenshots**

**Details about device, OS, browser (including versions)**

- Device: MacBook
- OS: macOS Monterey 12.1
- Browser: Safari 15.2
- Version: "@emdgroup-liquid/liquid": "^1.0.0-rc.2"

**Comment by borisdiakur** [comment]
Thanks @ElectricCookie While we're working on this issue please use `disabled={undefined}` as a workaround.

**Comment by borisdiakur** [comment]
This is apparently already fixed since 1.0.0-rc.19. @ElectricCookie Please upgrade to at least version of liquid.
