### ISSUE TITLE
Add search / autocomplete functionality/option to Select component

### ISSUE THREAD

**Issue by isopterix** [emdgroup-liquid/liquid#238]
**Is your feature request related to a problem? Please describe.**
Since this is currently missing the only option is to either (a) build something on your own or (b) us a dedicated form which offers both a filter field and a select to finally choose from.

**Describe the solution you'd like**
A combination of an Input component with a Select component which would allow the user to reduce the number of items to choose from in the list of possible options within the Select component.

**Describe alternatives you've considered**
Not yet.

![image](https://user-images.githubusercontent.com/5036868/149670786-d28d0cfd-f472-450c-a5fb-ecdf34f380dc.png)

**Comment by borisdiakur** [comment]
Thank you @isopterix We are tracking this in out [feature backlog](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+label%3Afeature+-label%3Adone+) now.

**Comment by borisdiakur** [comment]
<img width="463" alt="Screenshot 2022-06-22 at 14 53 45" src="https://user-images.githubusercontent.com/527049/175033843-c3838c31-f8ae-4a33-99ae-3c5941ae6a1e.png">

**Comment by ArpithaKamath** [comment]
Is this feature available yet? @borisdiakur
