### ISSUE TITLE
Unexpected token '?' - Condition symbol issue - on tailwind-preset.js file in node_modules folder

### ISSUE THREAD

**Issue by mohandeveloper2020** [emdgroup-liquid/liquid#241]
Hi Team,
I am getting an compilation error while doing npm start on a project using liquid oxygen.

version: **"@emdgroup-liquid/liquid": "^1.0.0-rc.23"**

![image](https://user-images.githubusercontent.com/28524550/149791085-0445cbee-2b0d-4a8c-b537-a95d82429a2e.png)

Then, I changed '**??**' symbol to '**&&**', it compiled successfully.

I am not sure, if this is the fix, can you please check.

Thanks and Regards,
Mohan Madheshwaran
IT-ACU | Merck India

**Comment by borisdiakur** [comment]
The `??` is a [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) and supported in Node >=14.0.0. My first suspicion is that you are using an older Node version. If this is not the case, we need to look at what is going on exactly in your project when you execute the start script. A [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) would help a lot to pinpoint the issue.

**Comment by mohandeveloper2020** [comment]
Yes Boris, I am using Node version 12.18.3
I will update the package to >=14 and check. Thank you.

**Comment by borisdiakur** [comment]
Closing this issue for now. Please reopen if the problem persists even after the Node upgrade.
