### ISSUE TITLE
React component for input field is not aware of the same paramaters available in the web-component

### ISSUE THREAD

**Issue by isopterix** [emdgroup-liquid/liquid#248]
It looks like some parameters in the LdInput component are missing, e.g. "rows", "cols". They are available with the web-component.

**Comment by renet** [comment]
Sorry, but I cannot reproduce this. Works well with the React bindings in the [liquid-sandbox-react-tailwind](https://github.com/emdgroup-liquid/liquid-sandbox-react-tailwind) using VS Code. Can you please provide some more information and in the best case provide a minimal reproduction repo? Thanks!

**Comment by isopterix** [comment]
Strange... now it seems to work here as well... maybe I was still having an old link in. Thanks for looking into it.
