### ISSUE TITLE
Disabled LdButton of type submit not rendering correctly

### ISSUE THREAD

**Issue by ElectricCookie** [emdgroup-liquid/liquid#249]
**Bug description**

The LdButton looses its styling when disabled

**Steps to reproduce the behavior**

In a react application: 

```tsx
<LdButton disabled={true} type="submit">
              Save
</LdButton>
```

**Expected behavior**

<img width="95" alt="image" src="https://user-images.githubusercontent.com/18628516/150335100-08667518-f0b5-4e79-90f7-7f65c5361554.png">

**Actual behavior**

<img width="95" alt="image" src="https://user-images.githubusercontent.com/18628516/150335054-aff61d46-e339-4778-aeef-7f9a9271083f.png">

**Details about device, OS, browser (including versions)**

- Device: Macbook
- OS: Mac OS Monterey
- Browser: Safari
- Version: @emdgroup-liquid/liquid": "^1.0.0-rc.27

**Comment by renet** [comment]
Thanks for reporting this. Seems like Safari applies default button styles to all elements that have the type="submit" attribute.

As a workaround you may use

```css
ld-button {
  -webkit-appearance: none !important;
}
```

Please also be aware that `"submit"` is the default value for the `type` prop and may also be omitted. This would resolve the problem, as well.

I'm already working on a fix that allows for explicit `type="submit"` (and `"button" and "reset") values without Safari applying it's own button styles.
