### ISSUE TITLE
React  - LdSelect does not fire onChange

### ISSUE THREAD

**Issue by ElectricCookie** [emdgroup-liquid/liquid#251]
**Bug description**

In a react application the onChange property is not called when the selection changes.

```tsx
<LdSelect
      onChange={(e) => {
        console.log(e);
      }}
    >
      <LdOption value="foo">Test</LdOption>
      <LdOption value="foo2">Test</LdOption>
    </LdSelect>
```

Will not log anything when changing the selection. In comparison onInput will fire. 

Device: Macbook
OS: Mac OS Monterey
Browser: Safari
Version: @emdgroup-liquid/liquid": "^1.0.0-rc.27

~Also maybe I'm just missing something. In the fired events where can I find the actual current value? e.target.value is not working for me.~ Found it: `e.nativeEvent.detail`

**Comment by ElectricCookie** [comment]
Possibly related #220

**Comment by renet** [comment]
Yes, this is related. Using `onInput` instead of `onChange` should do as a workaround. In the future we recommend using a custom event with React bindings that will be included in the next release.

**Comment by ElectricCookie** [comment]
Thanks for clarifying.  

However, I would love to have the selected items in the event as some property, as its quite an uncommon pattern to *read* props in react and would require a ref (which is kind of a hack).

Thanks!

**Comment by renet** [comment]
It is pretty common, even in React, to use the reference to the target element of an event to access the current value when a `change` event listener is triggered. In case of the `LdSelect` you will then be able to do it like this:

```tsx
const [selectedItems, setSelectedItems] = React.useState();
const handleInput = React.useCallback((event: InputEvent) => {
  setSelectedItems(event.target.selected);
}, []);

return <LdSelect /* ... */ onInput={handleInput} />;
```

Nevertheless we will pass the selected items as details for the new `ldinput` and `ldchange` events, coming with the next release. :)
