### ISSUE TITLE
Copy icon

### ISSUE THREAD

**Issue by juliuskittler** [emdgroup-liquid/liquid#258]
It would be useful to have a copy icon provided here: https://emdgroup-liquid.github.io/liquid/components/ld-icon/ So far, I could not find this option.

**Example**
![image](https://user-images.githubusercontent.com/39234739/151137615-c24de087-3fed-4398-af99-cb22b3e74f51.png)

**Comment by borisdiakur** [comment]
@NicolasBlock91 ☝️

**Comment by NicolasBlock91** [comment]
@borisdiakur the icon exists already, but I guess the import failed. https://www.figma.com/file/8GYcAOePm8Tt9qqJ7Gnv99/Liquid-Oxygen-(Share)?node-id=640%3A37311
@juliuskittler
