### ISSUE TITLE
Hyperlink icon

### ISSUE THREAD

**Issue by juliuskittler** [emdgroup-liquid/liquid#259]
It would be useful to have a hyperlink icon provided here: https://emdgroup-liquid.github.io/liquid/components/ld-icon/ So far, I could not find this option.

**Example**

![image](https://user-images.githubusercontent.com/39234739/151138042-03549a24-89b1-4961-b3ee-37df4f09303a.png)

**Comment by borisdiakur** [comment]
@NicolasBlock91 ☝️

**Comment by NicolasBlock91** [comment]
@borisdiakur @juliuskittler https://www.figma.com/file/8GYcAOePm8Tt9qqJ7Gnv99/Liquid-Oxygen-(Share)?node-id=640%3A37311 A Hyperlink icon is now available.
