### ISSUE TITLE
Link to Figma file is broken or not public

### ISSUE THREAD

**Issue by mkitzmann** [emdgroup-liquid/liquid#277]
**Bug description**

The link to the Liquid Figma file is broken or not public:
https://www.figma.com/file/8GYcAOePm8Tt9qqJ7Gnv99/Liquid-Oxygen-(Share)?node-id=3%3A14310

![image](https://user-images.githubusercontent.com/35574021/155493633-edacc857-a832-4ff2-abe1-5ca1043b190b.png)

Is this intended to be internal only?

**Comment by mkitzmann** [comment]
After learning about the limiting license (https://emdgroup-liquid.github.io/liquid/legal/license/), this question is no longer valid

**Comment by borisdiakur** [comment]
Hi @mkitzmann 
sorry for being late with my reply. You assumed right from the license that (in contrast to the code available on GitHub) there is only limited access to the Figma file, which is reserved for employees of Merck KGaA Darmstadt Germany and its vendors, meaning that only Figma users who's account email address ends with either @merckgroup.com or @emdgroup.com have access to the Figma file.

**Comment by borisdiakur** [comment]
We added a tooltip to the buttons linking to Figma in the documentation. It won't help users with touch devices, but at least those using a mouse.
