### ISSUE TITLE
Jagged look of fonts on Windows

### ISSUE THREAD

**Issue by borisdiakur** [emdgroup-liquid/liquid#278]
### Discussed in https://github.com/emdgroup-liquid/liquid/discussions/275

<div type='discussions-op-text'>

<sup>Originally posted by **isopterix** February 23, 2022</sup>
Is there anything we can do to make the fonts inside any of the controls look not as jagged when rendered on a Windows machine? Any recommendation?</div>

**Comment by borisdiakur** [comment]
@isopterix Ok, so I've done some initial testing on Windows using a VM and a remote desktop connection, both times on Edge. The fonts looked fine to me. Here is a screenshot:

<img width="1804" alt="Screenshot 2022-03-02 at 12 13 07" src="https://user-images.githubusercontent.com/527049/156352991-09595f8a-a2da-4adf-8bbf-ede7e87e7c9a.png">

So it looks like we still need more information to replicate the issue. Please provide...

**Screenshots**

If applicable, add screenshots to help explain your problem.

**Details about device, OS, browser (including versions)**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

Add any other context about the problem here. For instance, any relevant information on accessibility settings, such as screen sharpening, performance options etc. (see screenshot below).

![smoothscreenfonts](https://user-images.githubusercontent.com/527049/156354664-96f78db9-337b-40e7-bf69-dbd9058021ea.jpeg)

**Comment by isopterix** [comment]
@borisdiakur: here are some screenshots from a Windows 10 maschine running Chrome 98.0.4758.102.

As you can see the Merck font is not a particular problem, but the standard **light** Lato font which is used within the controls is. Here are some examples. Check out the numbers in particular. They all have rather strange blocks and dots on their top corner. I hope it still comes through despite of Githubs image compression...

It is clearly realted to the whay font-smoothing works in Windows compared to any other plattform.

![image](https://user-images.githubusercontent.com/5036868/156356553-308765d5-d3d8-466a-aeb4-54dc6d533fc4.png)

![image](https://user-images.githubusercontent.com/5036868/156356854-3dc47f9b-f26d-45d0-9d57-c257a1d076f5.png)

Font smoothing is on.

**Comment by isopterix** [comment]
Github is smoothing the image a bit... so it looks better here than what I see... And this has so far been the case on any Windows maschine I have used to check the framework.

**Comment by borisdiakur** [comment]
l can reproduce this in saucelabs. Working on it 🤓

**Comment by borisdiakur** [comment]
Hey @isopterix I think I have fixed the issue. I have replaced a broken font asset in our font hosting service. Can you please check on your side if the issue is gone? Please make sure to delete the cache.
