### ISSUE TITLE
Loading button overflows

### ISSUE THREAD

**Issue by ElectricCookie** [emdgroup-liquid/liquid#32]
**Describe the bug**
The loading indicator on the loading buttons overflows the parent. This is visible because the rounded corners become rectangular. 

**To Reproduce**
1. Go to https://emdgroup-liquid.github.io/liquid/components/ld-button/

**Expected behavior**
Button remains rounded while loading

**Screenshots**
![image](https://user-images.githubusercontent.com/18628516/133086732-3121dae1-7929-48b4-8637-a6b58d44614d.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Safari 
 - Version 14.1.22

**Comment by borisdiakur** [comment]
Thanks Yannick! 🙏
This is fixed on the develop branch now and will be published with the next rc release.
