### ISSUE TITLE
Select change event

### ISSUE THREAD

**Issue by m-suyash-kale** [emdgroup-liquid/liquid#341]
Select change not triggered.

A clear and concise description of the bug.

**Steps to reproduce the behavior**
On changing the value of the select component, the change event is not triggered.
[Example](https://codesandbox.io/s/select-change-jhn1ie?file=/src/App.tsx)

**Expected behavior**
The change event should trigger.

**Actual behavior**
The change event is not triggered.

**Comment by borisdiakur** [comment]
Hi @m-suyash-kale 👋
Please use `onLdchange`. See 
- https://emdgroup-liquid.github.io/liquid/components/ld-select/#events and 
- https://emdgroup-liquid.github.io/liquid/introduction/event-handling/

Cheers.
