### ISSUE TITLE
ld-select current value not visible due to incorrect z-order

### ISSUE THREAD

**Issue by borisdiakur** [emdgroup-liquid/liquid#373]
**Bug description**

Setting `will-change: transform` on a container containing an `ld-select` component leads to incorrect rendering of the select component (see screenshots below).

Without `will-change: transform`:
<img width="973" alt="Screenshot 2022-07-12 at 15 04 50" src="https://user-images.githubusercontent.com/527049/178496921-61b6f666-b0df-4b5b-bf08-ea1a50a96e1f.png">

With `will-change: transform`:
<img width="920" alt="Screenshot 2022-07-12 at 15 04 38" src="https://user-images.githubusercontent.com/527049/178496998-5fcd6601-4767-47e3-917b-56114ff4447a.png">

**Steps to reproduce the behavior**

1. Go to https://liquid.emd.design/liquid/components/ld-select/
2. Click on the select component

**Expected behavior**

"Pick a fruit" is still visible (even if used inside a container with `will-change: transform`).

**Actual behavior**

"Pick a fruit" is not visible.

**Details about device, OS, browser (including versions)**

- OS: macOS 12.4 
- Browser: Opera 88.0.4412.74 (arm64)

**Workaround**

Using [detached mode](https://liquid.emd.design/liquid/components/ld-select/#detached).

**Comment by ArpithaKamath** [comment]
Is it possible to view the dropdown options below the current selected value so that you can see what's selected. Also when it comes to filter, its easier if we can see what we type but in this case the entire options section covers the selected section. 
https://codesandbox.io/s/silly-wave-n38ed4?file=/src/App.js
