### ISSUE TITLE
LdTooltip doesn't trigger button event

### ISSUE THREAD

**Issue by ArpithaKamath** [emdgroup-liquid/liquid#406]
**Bug description**

When I try to implement button inside the tooltip, the onClick event doesn't work.

**Steps to reproduce the behavior**

https://codesandbox.io/s/ldtooltip-48el9i?file=/src/App.js

**Expected behavior**

When I click on download 1 the console should display appropriate message.

**Actual behavior**

No event is triggered. 

**Details about device, OS, browser (including versions)**

- OS: Windows
- Browser: Chrome
- Version: 2.4.3

**Comment by borisdiakur** [comment]
Hi @ArpithaKamath,
thanks for submitting this issue. I have written [additional documentation on how to solve this issue](https://liquid.emd.design/liquid/guides/troubleshooting/#popped-out-element-is-rendered-outside-application-root). Please have a look and let me know if I can help with this any further.
