### ISSUE TITLE
Background Cells should include 3 layer variants

### ISSUE THREAD

**Issue by toastedtoast** [emdgroup-liquid/liquid#417]
**Is your feature request related to a problem? Please describe.**
The Merck Brand allows Cell Patterns with 3 different colours. Additionally the pattern generator in the brand hub allows (beside size and position) rotating the pattern.

**Describe the solution you'd like**
Liquid Oxygen ld-bg-cell component should include the 3rd layer and documented variables for rotation and colors.

**Additional context**
These features should be opt-in and the default bg pattern should be based on the theme as it is atm.

**Comment by borisdiakur** [comment]
This repository is using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for features. This means:
- Feature requests are closed issues with `feature` label and `needed: votes` label.
- Bugs are open issues tagged with the bug label.

Upvote the description (top comment) of this issue with 👍 if you want it to be prioritized higher.
