### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by sankhlepawan** [emdgroup-liquid/liquid#443]
**Is your feature request related to a problem? Please describe.**
going forward our team is planning to start this for new project and we observed that table component is missing in this library

**Describe the solution you'd like**
can we have table component in this library ?

**Comment by borisdiakur** [comment]
Hi @sankhlepawan 👋

Your request already exists in our [feature backlog](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+label%3Afeature+-label%3Adone+). Please upvote [the table feature request](https://github.com/emdgroup-liquid/liquid/issues/139). Your vote helps us push things internally.

If you really need something fast and are working with React, you can reach out to @renet via Teams, he might have an alternative solution for you.

Please note: This repository is using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for features. This means:
- Feature requests are closed issues with `feature` label and `needed: votes` label.
- Bugs are open issues tagged with the bug label.

Upvote the description (top comment) of a feature request with 👍 if you want it to be prioritized higher.
