### ISSUE TITLE
LdSidenav Tooltip and Liquid Tooltip both are not working as expected 

### ISSUE THREAD

**Issue by mmevegar** [emdgroup-liquid/liquid#452]
Hi Team,

We have integrated Liquid in React/Typescript Project and using most of the Liquid design component. Currently we are facing issue with tooltip which is LdSidenav Tooltip as well as LdTooltip. On first load it is working fine but when we are accessing any other element were tetherOption is being used then all other tooltips are getting distorted I mean leaving the exact position and populating somewhere else on the Dom. 

Could you please suggest any solution  to resolve this issue.

![image](https://user-images.githubusercontent.com/108867182/207573846-6d03c739-3521-4b10-9781-5d7cdbd1e9cd.png)

![image](https://user-images.githubusercontent.com/108867182/207574110-021d994d-d21d-4ea4-9841-dc46e9e8d99e.png)

Thanks and Regards,
Muzamil Mevegar

**Comment by borisdiakur** [comment]
Hi @mmevegar. Thanks for submitting this issue 🙏
A [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) would help a lot to isolate the problem. Can you create one so I can have a look?

**Comment by borisdiakur** [comment]
I have created a minimal working example: https://stackblitz.com/github/emdgroup-liquid/liquid-issue-452
This looks very much like an [upstream issue in tether](https://github.com/shipshapecode/tether/issues/907) where two different bodyElements are used. The tooltips within the sidenav currently don't offer customization of their tether options. I'll try to change this, so that you'll maybe have a workaround. It would be great if you could confirm my suspicions so far by posting your custom tether options in a comment below.

**Comment by borisdiakur** [comment]
In @emdgroup-liquid/liquid v4.1.13 the `ld-sidenav-header`, `ld-sidenav-navitem` and `ld-sidenav-toggle-outside` components have a `tetherOptions` prop. Please try to use the same `bodyElement` options in all components using tether. The `bodyElement` should be an element wrapping your entire application (i.e. in a Next app this would be the element with id `"__next"`). Please let me know if this resolves your issue.

**Comment by mmevegar** [comment]
Hi @borisdiakur, Sorry for the delay in response. Actually I was busy in critical deliverables. Due to time crunch we fixed this issue with other work around and it got fixed. we did used **position: static** for outer element.

Note - We were getting lot of other issues while we tried to update the Liquid version. then we kept as is.

Thanks for your help and support.

**Comment by mmevegar** [comment]
Thanks for fixing this issue on prompt basis, definitely other teams will get benefit with this solution.

**Comment by borisdiakur** [comment]
Sure, no problem. I guess I can close this issue for now. Let me know if you find anything else or have questions.  😊
