### ISSUE TITLE
Add Timeline component

### ISSUE THREAD

**Issue by zemirco** [emdgroup-liquid/liquid#466]
It would be great to have some kind of Timeline component ⏲

**Ant Design**
https://ant.design/components/timeline
![image](https://user-images.githubusercontent.com/1132354/211784257-71368d76-ee26-4d1f-8b2c-83876330917a.png)

**Elastic UI**
https://elastic.github.io/eui/#/display/timeline
![image](https://user-images.githubusercontent.com/1132354/211784362-8e7ce670-2561-4ed0-ba91-3a4854a75930.png)

**VMware Clarity Design System**
https://clarity.design/documentation/timeline#examples
![image](https://user-images.githubusercontent.com/1132354/211784585-99984918-a23b-40bc-9149-f07869c83d5a.png)

**Salesforce Lightning Design System**
https://www.lightningdesignsystem.com/components/activity-timeline/?variant=base#site-main-content
![image](https://user-images.githubusercontent.com/1132354/211784748-9bd50744-0ee7-471e-96ed-92b967a12b77.png)

**Comment by borisdiakur** [comment]
Hi @zemirco
Thank you for your feature request! 🙏
Have you seen our [ld-stepper](https://liquid.merck.design/liquid/components/ld-stepper/) component? Is this what you're looking for? Or are you missing some specific feature?

**Comment by zemirco** [comment]
The stepper is indeed pretty close to what we'd like to see.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1132354/211908732-9a8e5034-f1b0-4282-b330-34b38cf0acd3.png">

Especially the example with custom icons is great!

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1132354/211909294-c9ef4b33-ecca-42ca-88ad-88a497a9cfea.png">

Unfortunately I didn't initially look at the stepper as I thought it's more about stepping through multiple actions to fulfill something. 🧐

One minor question that is related to #461. I saw it's possible to add links, e.g.

```html
<ld-stepper style="min-width: 25rem">
  <ld-step href="components/ld-stepper/#billing" done>Billing</ld-step>
  <ld-step href="components/ld-stepper/#shipping" done>Shipping</ld-step>
  <ld-step href="components/ld-stepper/#payment" current next last-active>Payment</ld-step>
  <ld-step href="components/ld-stepper/#summary" disabled>Summary</ld-step>
  <ld-step href="components/ld-stepper/#confirmation" disabled>Confirmation</ld-step>
</ld-stepper>
```

Would that also work with React and [React Router NavLink](https://reactrouter.com/en/main/components/nav-link)?

```tsx
<ld-stepper style="min-width: 25rem">
  <ld-step done>
    <NavLink to="components/ld-stepper/#billing">
      Billing
    </NavLink>
  </ld-step>
</ld-stepper>
```

**Comment by borisdiakur** [comment]
I'm not sure it would work with [`NavLink`](https://reactrouter.com/en/main/components/nav-link). I'd need to try this out and probably will in context of #461.
However, you could always use the [`useNavigate` hook](https://reactrouter.com/en/main/hooks/use-navigate) for the same purpose. It would look something like this:

```jsx
import { LdStep, LdStepper } from '@emdgroup-liquid/liquid/dist/react'
import * as React from 'react'
import { useNavigate } from 'react-router-dom'

const App: React.FC = () => {
  const navigate = useNavigate();

  const onStepClick = (ev: React.MouseEvent<HTMLLdStepElement, MouseEvent>) => {
    ev.preventDefault()
    const step = ev.target as HTMLLdStepElement
    if (!step.current && !step.disabled) {
      navigate((ev.target as HTMLLdStepElement).href)
    }
  }

  return (
    <LdStepper>
      <LdStep onClick={onStepClick} href="/foo" done>
        Billing
      </LdStep>
      <LdStep onClick={onStepClick} href="/bar" current next last-active>
        Payment
      </LdStep>
      <LdStep onClick={onStepClick} href="/baz" disabled>
        Confirmation
      </LdStep>
    </LdStepper>
  )
}

export default App
```

**Comment by toastedtoast** [comment]
@zemirco 
Do you consider this issue as completed as `ld-stepper` solves the requirements you had in mind?

**Comment by zemirco** [comment]
Yes! Let's close it for now 💪
