### ISSUE TITLE
bug: sidenav does not collapse correctly

### ISSUE THREAD

**Issue by vabe** [emdgroup-liquid/liquid#507]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

@emdgroup-liquid/liquid@4.4.3

### Framework bindings

React

### Current behavior

The `<LdSidenav>` or its related `<LdSidenavToggleOutside>` component does not work correctly when using `collapseTrigger="mouseout"`. 

**Scenario 1**: not in narrow mode, moving the mouse (cursor) outside the sidenav area collapses the panel, but it cannot be re-opened using the button. The button also has a different colour than expected (it shows up as if `:focus` and `:focus-visible` both were active).

![image](https://user-images.githubusercontent.com/3056548/218062262-19ae5110-7f13-4733-bd3a-6d373b2f76a7.png)

**Scenario 2**: in narrow mode, the collapse trigger works, unless one of the `<LdSidenavSubnav>` components contain a child that is not `<LdSidenavHeading>` or `<LdSidenavNavitem>`. For instance, having an `<LdTypo>` breaks the narrow mode completely, even though it has a parent that could be collapsed as described in the documentation (`<LdSidenavBack>`). It's not narrow anymore, and it cannot be re-opened by clicking on the button either (same as in Scenario 1)

Collapse with the button on the base level:
![image](https://user-images.githubusercontent.com/3056548/218063991-6efaf3ce-37ad-4b07-ada9-bed764696e03.png)

Expand and navigate to the subitem:
![image](https://user-images.githubusercontent.com/3056548/218063927-e788314f-fa77-476d-b8c9-9cc3630e5fbb.png)

Move the cursor outside, or collapse the sidenav with the button:
![image](https://user-images.githubusercontent.com/3056548/218062262-19ae5110-7f13-4733-bd3a-6d373b2f76a7.png)

**Scenario 3**: in narrow mode, the sidenav can be re-opened even if it has a different child (e.g. `<LdTypo>`) if the `collapseTrigger` is not applied, but the sidenav turns into its non-narrow mode on collapse even though it has an `<LdSidenavBack>` inside.

### Expected behavior

Scenario 1: after collapsing an `<LdSidenav>` in non-narrow mode using the `collapseTrigger`, I should be able to re-open it.

Scenario 2: after collapsing an `<LdSidenav>` in narrow mode using the `collapseTrigger` (either by pressing the button, or moving the cursor outside, but having that prop set), I should see a collapsed, narrow `<LdSidenav>` and should be able to re-open it.

Scenario 3: after collapsing an `<LdSidenav>` in narrow mode using the buttons, I should see a collapsed, narrow `<LdSidenav>`, not the non-narrow version.

### Steps to reproduce

1. Set up a React-based project (or use the provided sandbox from the documentation)
2. Update Liquid version to latest (`@emdgroup-liquid/liquid@4.4.3`)
3. Import and combine the necessary components to build a sidenav
    ```
    import {
      LdSidenav,
      LdSidenavBack,
      LdSidenavHeader,
      LdSidenavHeading,
      LdSidenavNavitem,
      LdSidenavSlider,
      LdSidenavSubnav,
      LdSidenavToggleOutside,
      LdTypo,
    } from '@emdgroup-liquid/liquid/dist/react'
    ```
4. Add `collapseTrigger="mouseout`
5. Check the behaviour
6. Add `narrow` to the sidenav
7. Replace one of the sub-navigation items with another component (e.g `<LdTypo>`)
8. Navigate to that sub-item
9. Check the behaviour
10. Remove `collapseTrigger="mouseout`
11. Navigate to the sub-navigation with another component
12. Collapse the sidenav

### Code reproduction URL

https://stackblitz.com/edit/github-ss8jru?file=src/components/Sidebar/Sidebar.tsx

### Additional information

In the sandbox, there's a `Sidebar` and a `SidebarNarrow` component prepared for testing. In the `SidebarNarrow`, the "Algorithms and data structures" menu item has the `<LdTypo>` inside.

The `App.tsx` includes both components, one is commented out.

**Comment by borisdiakur** [comment]
@vabe Thank you for taking the time to create this issue. Your reproduction example was really helpful in fixing it! 🙏
