### ISSUE TITLE
bug: Select options are not visible when LdSelect is used inside of the LdModal

### ISSUE THREAD

**Issue by mdekhtiarenko** [emdgroup-liquid/liquid#608]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

4.7.10

### Framework bindings

React

### Current behavior

Options are placed under the modal.
<img width="563" alt="Screenshot 2023-03-29 at 17 26 05" src="https://user-images.githubusercontent.com/16037597/228574986-1ab091fc-5725-4c80-9622-c35b85f9b5d2.png">

### Expected behavior

Options should be visible.

### Steps to reproduce

1) Put LdSelect inside of the modal
2) Run app

Check out my sample app.

### Code reproduction URL

https://github.com/mdekhtiarenko/liquid-design-test

**Comment by borisdiakur** [comment]
Hi @mdekhtiarenko,
we have a trouble shooting page targeting this specific issue: https://emdgroup-liquid.github.io/liquid/guides/troubleshooting/popped-out-element-is-rendered-in-wrong-container/
Have you already had a look at it?

**Comment by borisdiakur** [comment]
I'm closing this issue for now. Feel free to re-open / open a new issue, if you're still stuck with this.
