### ISSUE TITLE
bug: Tooltip position is being calculated wrong after using inside of the modal

### ISSUE THREAD

**Issue by mdekhtiarenko** [emdgroup-liquid/liquid#609]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

5.0.0

### Framework bindings

React

### Current behavior

After showing tooltip inside of the modal with `tetherOptions` specified tooltips outside of the modal calculte poper position incorrect.
It can be seen in the sample project I included.

### Expected behavior

Tooltip should be placed above element after usage inside of the modal.

### Steps to reproduce

1) Run project
2) Hover on info icon - tooltip shoud be shown correctly
3) Open modal and hover on info icon inside of the modal - tooltip shoud be shown correctly
4) Close modal and hover on the icon from step # 2 - tooltip will be invisible or placed incorrectly

### Code reproduction URL

https://github.com/mdekhtiarenko/liquid-design-test

**Comment by mdekhtiarenko** [comment]
Hi @borisdiakur 
Thanks for checking this that fast.
Unfortunantly I can't confirm that it was fixed in 5.0.1.

**Comment by borisdiakur** [comment]
@mdekhtiarenko I'm sorry, 5.0.2 will fix this. The patch range was wrong. I needed to add a `^` to fix this. The `5.0.2` release is on its way. Should take only a couple of minutes.

**Comment by mdekhtiarenko** [comment]
@borisdiakur works like charm! Thanks a lot!
