### ISSUE TITLE
bug: The selectable table without LdTableHead produces the Error on the item selection. 

### ISSUE THREAD

**Issue by ssuchkov** [emdgroup-liquid/liquid#635]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

5.1.0

### Framework bindings

React

### Current behavior

Error on selecting the item. 
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at LdTable.handleTableSelect (ld-table.entry-JVDZOEJ6.js?v=cbf46b15:62:40)
    at HostElement.<anonymous> (chunk-UOJQOYET.js?v=cbf46b15:1013:43)
    at emitEvent (chunk-UOJQOYET.js?v=cbf46b15:163:7)
    at Object.emit (chunk-UOJQOYET.js?v=cbf46b15:152:14)
    at LdTableRow.handleSelect (ld-table-row.entry-YP4ZLCFL.js?v=cbf46b15:30:28)
    at LdTableRow.onSelectInput (ld-table-row.entry-YP4ZLCFL.js?v=cbf46b15:38:12)`

### Expected behavior

Item is selected. 

### Steps to reproduce

Create the table having no table header 
    
And select the item then. 

### Code reproduction URL

https://stackblitz.com/edit/github-nuye2o?file=src/App.tsx

**Comment by ssuchkov** [comment]
incorrect link for reproduce https://stackblitz.com/edit/github-nuye2o?file=src/App.tsx

**Comment by borisdiakur** [comment]
Thank you for reporting this @ssuchkov 🙏
v5.1.1 will include a fix and is [about to be released](https://github.com/emdgroup-liquid/liquid/actions/runs/4687113437).
