### ISSUE TITLE
bug: `ld-cookie-consent` "reject all" button toggles also disabled/necessary categories

### ISSUE THREAD

**Issue by renet** [emdgroup-liquid/liquid#664]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

5.3.1

### Framework bindings

no bindings

### Current behavior

When clicking on the "Reject all" button in the settings modal of the `ld-cookie-consent` component, every cookie category switches to `checked: false`, even the categories that are marked as `disabled` (mandatory). I assume that the same would happen, when clicking on the "Reject all" on the first modal, when config contains `rejectable: true`.

### Expected behavior

Mandatory (`disabled`) categories can never be unchecked, not even when clicking a "Reject all" button.

### Steps to reproduce

1. Open consent layer (first example on the docs page)
2. Click on "Cookie settings".
3. Click on "Reject all" button.
4. Open the consent layer of the same example, again.
5. Click on "Cookie settings".
6. "Necessary" category is unchecked, even though it was previously disabled.

### Code reproduction URL

https://liquid.merck.design/liquid/components/ld-cookie-consent/

**Comment by borisdiakur** [comment]
Well, I think this is more of a UX question. To me, "Reject __all__" means I want to reject __all__ cookies, even the necessary ones. This is similar to when you tell your browser to block all cookies, even if then some features will not work anymore on some sites. If you don't want to reject the necessary ones, then you select specifically what you want to reject. If I recall correctly, the cookie consent component is programmed in a way that it allows you to "re-enable" the rejected cookies, even if their toggle was previously disabled.

**Comment by renet** [comment]
I understand. I strongly disagree, because with this behavior, the component behaves differently than any other cookie consent layer I've yet spotted out there. Even when "rejecting all" cookies, I assume, necessary cookies cannot be rejected. Because if they could with the site's own functionality, how would they be necessary then? Also, afaik most pages rather offer a "accept only necessary cookies" button instead of a "reject all" button - but that's probably only a label, anyway. We should discuss this within the team.

**Comment by borisdiakur** [comment]
You are probably right about the inconsistent behavior: If a toggle is disabled, it should stay disabled. However, if we disallow rejecting the necessary cookies, we should rename the button to something like "Reject all non-necessary" or something the like.
