### ISSUE TITLE
bug: `ld-cookie-consent` state does not update when manually toggling categories

### ISSUE THREAD

**Issue by renet** [emdgroup-liquid/liquid#665]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

5.3.1

### Framework bindings

no bindings

### Current behavior

- The toggle state does not update when manually (de)selecting some/all categories and then clicking the "Accept cookies" or the "Accept all" button.
- Also there are cases where clicking on the "Reject all" button does not deselect previously manually selected categories.
- And there are also cases where clicking on the "Accept selected" button toggles a previously manually deselected category and makes it selected again.

### Expected behavior

- When clicking on "Accept all" or "Accept cookies", all categories are selected ...
- When clicking on "Reject all", all categories (except for the necessary/disabled ones) are deselected ...
- When clicking on "Accept selected", all categories are in the same state as before ...

... when opening the cookie settings again, no matter what manual state changes have been applied before clicking the button.

#### Accepting all cookies:

1. Open `ld-cookie-consent` modal (e.g. first example in the docs)
2. Click on "Cookie settings"
3. Manually uncheck at least one of the categories
4. Click on "Accept all" button
5. Open the modal of the same example again
6. Click on "Cookie settings"
7. Not all categories are checked

or

1. Follow previous steps 1-3
2. Click on the close icon of the modal
3. Click on "Accept cookies" button
4. Open the modal of the same example again
5. Click on "Cookie settings"
6. Not all categories are checked

#### Rejecting all cookies:

1. Open `ld-cookie-consent` modal (e.g. first example in the docs)
2. Click on "Cookie settings"
3. Click on "Reject all"
4. Open the modal of the same example again
5. Click on "Cookie settings"
6. Toggle one category to be checked
7. Click on "Reject all"
8. Open the modal of the same example again
9. Click on "Cookie settings"
10. Previously checked category is still checked

#### Accepting selected categories:

1. Follow steps 1-9 of "Rejecting all cookies"
2. Toggle the previously checked category to be unchecked
3. Click on "Accept selected"
4. Open the modal of the same example again
5. Click on "Cookie settings"
6. Previously unchecked category is checked again

### Code reproduction URL

https://liquid.merck.design/liquid/components/ld-cookie-consent/

**Comment by borisdiakur** [comment]
We need to change the `onLdChangle` handler of the `ld-toggle` component, so that it always assigns a new `Set` to `this.selectedCategories`. It should look like this:

```tsx
const selectedCategoriesArray = [...this.selectedCategories]
if (this.selectedCategories.has(category.toggle.value)) {
 selectedCategoriesArray.splice(
selectedCategoriesArray.indexOf(category.toggle.value), 1
 )
} else {
 selectedCategoriesArray.push(category.toggle.value)
}
this.selectedCategories = new Set(selectedCategoriesArray)
```
