### ISSUE TITLE
bug: onClick handler not called on LdMenuitem

### ISSUE THREAD

**Issue by vvision** [emdgroup-liquid/liquid#745]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

5.6.0

### Framework bindings

React

### Current behavior

`onClick` handler are not called on `LdMenuitem` component.

### Expected behavior

`onClick` handler are called on `LdMenuitem` component.

### Steps to reproduce

Minimalistic React based reproduction example:
```javascript
import {
  LdButton,
  LdMenuitem,
  LdContextMenu
} from "@emdgroup-liquid/liquid/dist/react";

export default function App() {
  const onClick = (ev, id) => {
    console.info('click', id, ev)
  }
  return (
    <>
      <LdContextMenu>
        <LdButton slot="trigger">Open menu</LdButton>
        <LdMenuitem onClick={(ev) => onClick(ev, 1)}>Menu item 1</LdMenuitem>
        <LdMenuitem onClick={(ev) => onClick(ev, 2)}>Menu item 2</LdMenuitem>
        <LdMenuitem onClick={(ev) => onClick(ev, 3)}>Menu item 3</LdMenuitem>
        <LdMenuitem>
          <LdButton onClick={(ev) => onClick(ev, 4)}>Menu button 4</LdButton>
        </LdMenuitem>
      </LdContextMenu>
    </>
  );
}
```

1. Open the menu.
2. Click on any item inside the menu.
3. Check the console.

### Code reproduction URL

https://github.com/vvision/bug-liquid-handler-menu

### Additional information

Hello,

I'm unable to get a click event on a `LdMenuitem` component.
I assume it's a bug, or I'm missing something.

If there is another way to handle clicks on `LdMenuitem` component to act on user interaction, please let my know.

**Comment by borisdiakur** [comment]
Hi @vvision ,
you need to set a `tetherOptions` prop on the `LdContextMenu` element:

```ts
const tetherOptions = {
  bodyElement: document.getElementById('root')
}
```

```tsx
<LdContextMenu tetherOptions={tetherOptions}>
```

See https://liquid.merck.design/liquid/guides/troubleshooting/popped-out-element-is-rendered-in-wrong-container/

**Comment by vvision** [comment]
Thanks @borisdiakur for the insight!

We are indeed using `tetherOptions` on `LdSelect` for option list placement, but I hadn't realized it was also the go-to solution for click handlers.
