### ISSUE TITLE
feat: add download attribute for LdLink

### ISSUE THREAD

**Issue by mdekhtiarenko** [emdgroup-liquid/liquid#848]
### Prerequisites

- [X] I know [how to contribute a proper feature request](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#requesting-new-features).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing feature requests](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) that already request this feature, without success.

### Describe the feature request

<a> has a download attribute, making the browser treat this link as a file that should be downloaded. Our counterpart <LdLink> doesn't have the ability to pass this attribute. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

### Describe the use case

The browser treats LdLink with a path to a downloadable file as a route which results in the navigation to non-existing page instead of a download.
Here is an example:
`<LdLink href="/files/MembersImportExample.csv">Example</LdLink>` - causes navigation

`<a download href="/files/MembersImportExample.csv">Example</a>` - causes download

### Describe preferred solution

Add download attribute to LdLink so I can use it like that:
`<LdLink download href="/files/MembersImportExample.csv">Example</LdLink>`

**Comment by borisdiakur** [comment]
Thanks for this feature request! 

While we're working on it, here is a workaround:

```
<LdLink href="/files/MembersImportExample.csv" {...{ download: true }}>Example</LdLink>
```
