### ISSUE TITLE
feat: grouping feature to the Select component

### ISSUE THREAD

**Issue by mdekhtiarenko** [emdgroup-liquid/liquid#879]
### Prerequisites

- [X] I know [how to contribute a proper feature request](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#requesting-new-features).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing feature requests](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) that already request this feature, without success.

### Describe the feature request

Add grouping feature to the LdSelect component.

### Describe the use case

For one of our features, we need a multi-select with the ability to group items. Something like shown on this screenshot but in LD theme. Ideally, the group would have its own checkbox that gonna select all of the items in this group. 
![image](https://github.com/emdgroup-liquid/liquid/assets/16037597/d0f2ebe5-b47f-41f8-835e-8b19e0ac2e46)

**Comment by borisdiakur** [comment]
Thanks for the feature request! 👍

There are still a couple of open questions that need to be considered before the implementation:

- What happens to a selected group when a group option is deselected - is it then still selected or not, or partially? I would suggest setting the group checkbox to [indeterminate](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate) in case of a partial selection of group options.
- How do other features of the `ld-select` component behave in combination with the new feature (e.g. filter, multiselect mode, etc.)? I think we should filter on both, group values and group option values. In multiselect mode we only should list group option values in the selection list.
- How is form data written (do you only send the group option values, or also the group value as well)? I would probably handle the group as an [optgroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) and send only the values of the group options.
